# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
